on:
  push:
    branches:
      - main

name: Render and Publish

permissions: 
    contents: write
    pages: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install graphviz
        run: sudo apt install -y graphviz
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::withr

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # DVC I lecture notebook assumes git init creates main as default branch
      - name: Change default Git branch name to main
        run: git config set --global init.defaultBranch main

      - name: Publish to GitHub Pages (and render) 
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
